package web.MySummerGarage.model;

//CLASSE ENUM PARA DEFINIR O STATUS DE UM PAGAMENTO DE UMA VENDA DE CARRO, SEJA PENDENTE, PROCESSANDO, CONCLUIDO OU CANCELADO
public enum StatusPagamento {
    PENDENTE, PROCESSANDO, CONCLUIDO, CANCELADO
}